# Generated by Django 4.2.1 on 2023-05-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=10)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('effective_date_of_registration', models.DateField(blank=True)),
                ('constitution_of_bussiness', models.CharField(max_length=100)),
                ('gstin_uin_status', models.CharField(max_length=100)),
                ('taxpayer_type', models.CharField(max_length=100)),
                ('administrative_office', models.TextField()),
                ('other_office', models.TextField()),
                ('principle_place', models.TextField()),
                ('adhaar_authenticated_status', models.BooleanField(default=False)),
                ('ekyc_status', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=12)),
                ('additional_trade_name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
