# Generated by Django 4.2.1 on 2023-06-26 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetCapacity', models.IntegerField()),
                ('assetLocation', models.CharField(max_length=255, null=True)),
                ('assetName', models.CharField(max_length=255, unique=True)),
                ('assetPincode', models.IntegerField()),
                ('assetRegistrationNumber', models.CharField(blank=True, max_length=255)),
                ('assetState', models.CharField(blank=True, max_length=255)),
                ('fuelType', models.CharField(blank=True, default='Diesel', max_length=255)),
                ('typeOfAsset', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('diesel_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('order_status', models.CharField(default='ordered', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ordered_user_type', models.CharField(max_length=100)),
                ('order_type', models.CharField(default='client', max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.assets')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=255)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.CharField(default='manager', max_length=10)),
                ('number', models.CharField(max_length=12)),
                ('monthly_purchase_cost', models.IntegerField(blank=True, null=True)),
                ('monthly_purchase_quantity', models.IntegerField(blank=True, null=True)),
                ('total_outstanding', models.IntegerField(blank=True, null=True)),
                ('total_purchase_cost', models.IntegerField(blank=True, null=True)),
                ('total_purchase_quantity', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('effective_date_of_registration', models.DateField(null=True)),
                ('constitution_of_bussiness', models.CharField(blank=True, max_length=100)),
                ('gstin_uin_status', models.CharField(blank=True, max_length=100)),
                ('taxpayer_type', models.CharField(blank=True, max_length=100)),
                ('administrative_office', models.TextField(blank=True)),
                ('other_office', models.TextField(blank=True)),
                ('principle_place', models.TextField(blank=True)),
                ('adhaar_authenticated_status', models.CharField(blank=True, default=False, max_length=50)),
                ('ekyc_status', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(max_length=100)),
                ('additional_trade_name', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100)),
                ('payment_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_month', models.CharField(max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='staff_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_incharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssetLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True)),
                ('location2', models.TextField(blank=True)),
                ('location3', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
