# Generated by Django 4.2.1 on 2023-06-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlocations',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='assetlocations',
            name='location3',
        ),
        migrations.AlterField(
            model_name='assets',
            name='assetLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.assetlocations'),
        ),
    ]
