# Generated by Django 4.2.1 on 2023-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_company_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='additional_trade_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='adhaar_authenticated_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='administrative_office',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='constitution_of_bussiness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='effective_date_of_registration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ekyc_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='gstin_uin_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_office',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='principle_place',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='taxpayer_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
