# Generated by Django 4.2.1 on 2023-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_assetlocations_location2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
