# Generated by Django 4.2.1 on 2023-05-24 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_company_additional_trade_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetCapacity', models.IntegerField()),
                ('assetIncharge', models.CharField(max_length=255, null=True)),
                ('assetInchargeName', models.CharField(max_length=255, null=True)),
                ('assetInchargeNumber', models.CharField(max_length=255, null=True)),
                ('assetLocation', models.CharField(max_length=255, null=True)),
                ('assetName', models.CharField(max_length=255, null=True)),
                ('assetPincode', models.IntegerField()),
                ('assetRegistrationNumber', models.CharField(max_length=255, null=True)),
                ('assetState', models.CharField(max_length=255, null=True)),
                ('fuelType', models.CharField(max_length=255, null=True)),
                ('typeOfAsset', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
