# Generated by Django 4.2.1 on 2023-07-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_payments_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='additional_trade_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adhaar_authenticated_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='constitution_of_bussiness',
        ),
        migrations.RemoveField(
            model_name='user',
            name='effective_date_of_registration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ekyc_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gstin_uin_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='principle_place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='taxpayer_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trade_name',
        ),
    ]
