# Generated by Django 4.2.1 on 2023-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_user_additional_trade_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legal_name',
        ),
        migrations.AddField(
            model_name='user',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
