# Generated by Django 4.2.1 on 2023-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='assetIncharge',
        ),
        migrations.AlterField(
            model_name='assets',
            name='assetInchargeName',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='assetInchargeNumber',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='assetState',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
