# Generated by Django 4.2.1 on 2023-07-06 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_user_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='administrative_office',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monthly_purchase_cost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monthly_purchase_quantity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_office',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_outstanding',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_purchase_cost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_purchase_quantity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trade_name',
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('administrative_office', models.TextField(blank=True)),
                ('other_office', models.TextField(blank=True)),
                ('gstin', models.CharField(max_length=100)),
                ('monthly_purchase_cost', models.IntegerField(blank=True, null=True)),
                ('monthly_purchase_quantity', models.IntegerField(blank=True, null=True)),
                ('total_outstanding', models.IntegerField(blank=True, null=True)),
                ('total_purchase_cost', models.IntegerField(blank=True, null=True)),
                ('total_purchase_quantity', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
