# Generated by Django 4.2.1 on 2023-05-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_assets_fueltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='fuelType',
            field=models.CharField(blank=True, default='Diesel', max_length=255),
        ),
    ]
