# Generated by Django 4.2.1 on 2023-07-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_remove_user_administrative_office_remove_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='user',
            new_name='company',
        ),
    ]
