# Generated by Django 4.2.1 on 2023-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_rename_user_companyinfo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='diesel_price',
            field=models.FloatField(null=True),
        ),
    ]
