# Generated by Django 4.2.1 on 2023-07-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_companyinfo_diesel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='discount_price',
            field=models.FloatField(null=True),
        ),
    ]
