# Generated by Django 4.2.1 on 2023-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_company_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='asset_incharge',
            field=models.CharField(blank=True, default='Heavy vehicle', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
