# Generated by Django 4.2.3 on 2023-07-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_alter_order_discount_price_alter_order_saved_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Core.order'),
        ),
    ]
