# Generated by Django 4.2.1 on 2023-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_remove_company_location_assetlocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
