# Generated by Django 4.2.3 on 2023-07-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_payments_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.order'),
        ),
    ]
