# Generated by Django 4.2.1 on 2023-05-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_company_asset_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
