# Generated by Django 4.2.3 on 2023-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_payments_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
