# Generated by Django 4.2.1 on 2023-05-30 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_remove_assets_assetinchargename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='staffs_incharge',
        ),
        migrations.AddField(
            model_name='assets',
            name='staffs_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_incharge', to=settings.AUTH_USER_MODEL),
        ),
    ]
