# Generated by Django 4.2.3 on 2023-07-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_payments_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='total_outstanding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
