# Generated by Django 4.2.1 on 2023-05-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_remove_assets_staffs_incharge_assets_staffs_incharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='staffs_incharge',
            new_name='staff_incharge',
        ),
    ]
