# Generated by Django 4.2.1 on 2023-05-31 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_rename_staffs_incharge_assets_staff_incharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='asset_incharge',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(default='Ordered', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ordered_user_type', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
