# Generated by Django 4.2.1 on 2023-05-31 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_remove_company_asset_incharge_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.assets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
