# Generated by Django 4.2.3 on 2023-07-19 07:50

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_totalizerreadings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalizerreadings',
            name='image',
            field=models.FileField(upload_to=Core.models.TotalizerReadings.upload_to),
        ),
    ]
