# Generated by Django 4.2.3 on 2023-07-20 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_alter_totalizerreadings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
