# Generated by Django 4.2.1 on 2023-06-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_company_monthly_purchase_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='total_purchase_quantuty',
            new_name='total_purchase_quantity',
        ),
    ]
