# Generated by Django 4.2.3 on 2023-07-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_order_ordered_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_admin',
        ),
    ]
