# Generated by Django 4.2.1 on 2023-06-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_rename_total_purchase_quantuty_company_total_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocations',
            name='location2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetlocations',
            name='location3',
            field=models.TextField(blank=True),
        ),
    ]
