# Generated by Django 4.2.3 on 2023-07-20 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_romulusassets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romulusassets',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='romulusassets',
            name='reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
