# Generated by Django 4.2.1 on 2023-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_payments_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='monthly_purchase_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='monthly_purchase_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_purchase_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_purchase_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
