# Generated by Django 4.2.3 on 2023-07-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_alter_romulusassets_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='romulusassets',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='romulusassets',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
