# Generated by Django 4.2.1 on 2023-06-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_alter_company_monthly_purchase_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adhaar_authenticated_status',
            field=models.CharField(blank=True, default=False, max_length=50),
        ),
    ]
