# Generated by Django 4.2.1 on 2023-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_alter_company_adhaar_authenticated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='client', max_length=100),
        ),
    ]
