# Generated by Django 4.2.1 on 2023-06-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Core.order'),
            preserve_default=False,
        ),
    ]
