# Generated by Django 4.2.1 on 2023-06-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0029_payments_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assetName',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
