# Generated by Django 4.2.3 on 2023-07-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0032_order_asset_orderdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.romulusassets'),
        ),
    ]
