# Generated by Django 4.2.3 on 2023-07-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0033_order_delivered_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalizerreadings',
            old_name='reading',
            new_name='left_reading',
        ),
        migrations.RenameField(
            model_name='totalizerreadings',
            old_name='reading2',
            new_name='right_reading',
        ),
    ]
