# Generated by Django 4.2.3 on 2023-07-22 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_rename_reading_totalizerreadings_left_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdistribution',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='totalizerreadings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='RomulusDeliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('delivery_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.romulusassets')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.order')),
            ],
        ),
    ]
