# Generated by Django 4.2.3 on 2023-07-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0035_orderdistribution_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdistribution',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Core.romulusdeliveries'),
            preserve_default=False,
        ),
    ]
