# Generated by Django 4.2.3 on 2023-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_orderdistribution_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='manager', max_length=30),
        ),
    ]
