# Generated by Django 4.2.3 on 2023-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0037_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='romulusdeliveries',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
