# Generated by Django 4.2.3 on 2023-07-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0039_romulusdeliveries_secondary_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='romulusdeliveries',
            old_name='delivery_vehicle',
            new_name='bowser',
        ),
    ]
