# Generated by Django 4.2.3 on 2023-07-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0040_rename_delivery_vehicle_romulusdeliveries_bowser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='romulusdeliveries',
            old_name='secondary_staff',
            new_name='second_staff',
        ),
    ]
