# Generated by Django 4.2.3 on 2023-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0041_rename_secondary_staff_romulusdeliveries_second_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='romulusdeliveries',
            name='by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
