# Generated by Django 4.2.3 on 2023-07-23 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0042_romulusdeliveries_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnTimeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.romulusdeliveries')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
