# Generated by Django 4.2.3 on 2023-07-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0043_ontimedelivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnTimeDelivery',
        ),
    ]
