# Generated by Django 4.2.3 on 2023-07-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0044_delete_ontimedelivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='romulusdeliveries',
            old_name='delivery_staff',
            new_name='staff_1',
        ),
        migrations.RenameField(
            model_name='romulusdeliveries',
            old_name='second_staff',
            new_name='staff_2',
        ),
    ]
