# Generated by Django 4.2.3 on 2023-07-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0045_rename_delivery_staff_romulusdeliveries_staff_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdistribution',
            name='order',
        ),
    ]
