# Generated by Django 4.2.3 on 2023-07-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0046_remove_orderdistribution_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdistribution',
            name='company',
        ),
    ]
