# Generated by Django 4.2.3 on 2023-07-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0047_remove_orderdistribution_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdistribution',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
