# Generated by Django 4.2.3 on 2023-07-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0048_alter_orderdistribution_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdistribution',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution', to='Core.romulusdeliveries'),
        ),
        migrations.AlterField(
            model_name='romulusdeliveries',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='Core.order'),
        ),
    ]
