# Generated by Django 4.2.3 on 2023-07-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0050_alter_order_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetLocations',
            new_name='ClientLocations',
        ),
    ]
