# Generated by Django 4.2.3 on 2023-07-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0052_alter_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romulusdeliveries',
            name='bowser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.romulusassets'),
        ),
    ]
