# Generated by Django 4.2.3 on 2023-07-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0053_alter_romulusdeliveries_bowser'),
    ]

    operations = [
        migrations.AddField(
            model_name='romulusassets',
            name='duel_totalizer',
            field=models.BooleanField(default=False),
        ),
    ]
