# Generated by Django 4.2.3 on 2023-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0054_romulusassets_duel_totalizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_vehicle',
        ),
        migrations.AddField(
            model_name='order',
            name='approved_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
