# Generated by Django 4.2.3 on 2023-07-27 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0057_deliverytotalizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_no', models.CharField(max_length=255)),
                ('dispatch_doc_no', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('paid_amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
