# Generated by Django 4.2.3 on 2023-07-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0059_invoice_invoice_image_alter_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Core.order'),
            preserve_default=False,
        ),
    ]
