# Generated by Django 4.2.3 on 2023-07-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0060_invoice_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_image',
            new_name='invoice_file',
        ),
    ]
