# Generated by Django 4.2.3 on 2023-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0061_rename_invoice_image_invoice_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
