# Generated by Django 4.2.3 on 2023-07-31 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0063_alter_invoice_invoice_no_alter_invoice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_datetime', models.DateTimeField()),
                ('payment_amount', models.FloatField()),
                ('partial_amount', models.FloatField(null=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('full_payment_invoices', models.ManyToManyField(blank=True, null=True, related_name='full_payments', to='Core.invoice')),
                ('partial_payment_invoices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.invoice')),
            ],
        ),
    ]
