# Generated by Django 4.2.3 on 2023-07-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0065_payment_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='partial_payment_invoices',
            new_name='partial_payment_invoice',
        ),
    ]
