# Generated by Django 4.2.3 on 2023-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0066_rename_partial_payment_invoices_payment_partial_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='server_payment_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
