# Generated by Django 4.2.3 on 2023-08-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0071_transaction_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalizerreadings',
            old_name='total_reading',
            new_name='single_reading',
        ),
    ]
