# Generated by Django 4.2.3 on 2023-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0072_rename_total_reading_totalizerreadings_single_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalizerreadings',
            name='left_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
