# Generated by Django 4.2.3 on 2023-08-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0074_romulusassets_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romulusdeliveries',
            name='bowser',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='Core.romulusassets'),
            preserve_default=False,
        ),
    ]
