# Generated by Django 4.2.3 on 2023-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0075_alter_romulusdeliveries_bowser'),
    ]

    operations = [
        migrations.AddField(
            model_name='romulusdeliveries',
            name='totalizer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
