# Generated by Django 4.2.3 on 2023-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0076_romulusdeliveries_totalizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='romulus', max_length=100),
        ),
    ]
