# Generated by Django 4.2.3 on 2023-08-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0077_order_is_billable_alter_order_order_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
